### ISSUE TITLE
sshd checks should also read /etc/ssh/sshd_config.d/*.conf

### ISSUE THREAD

**Issue by fmarier** [ParetoSecurity/pareto-linux#25]
On my machine, the following gets flagged:

>  ✗  Access Security: SSH Server Configuration is Secure > SSH configuration is not secure.

which is due to the fact that the required setting are not present in `/etc/ssh/sshd_config`:
```
$ grep PasswordAuthentication /etc/ssh/sshd_config
#PasswordAuthentication yes
# PasswordAuthentication.  Depending on your PAM configuration,
# PAM authentication, then enable this but set PasswordAuthentication

$ grep PermitRootLogin /etc/ssh/sshd_config
#PermitRootLogin prohibit-password
# the setting of "PermitRootLogin without-password".
```

However, these settings are enabled in separate config files in `/etc/ssh/sshd_config.d/`:
```
$ grep PasswordAuthentication /etc/ssh/sshd_config.d/*
/etc/ssh/sshd_config.d/local.conf:PasswordAuthentication no

$ grep PermitRootLogin /etc/ssh/sshd_config.d/*
/etc/ssh/sshd_config.d/mozilla_ssh_recommendations.conf:PermitRootLogin no
```

**Comment by dz0ny** [comment]
We now have the capability to read runtime settings, which should effectively prevent any form of configuration manipulation from leading to inaccurate reporting.

**Comment by zupo** [comment]
@fmarier can you please install the latest version and try again?

**Comment by fmarier** [comment]
I no longer have that warning with Pareto `0.0.54@7dd86a87be7b45be490bb180b284f07f8a5c94df 2024-12-18T19:52:49Z`.
